# Generated by Django 5.0.7 on 2024-07-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='baseapp.topic'),
        ),
    ]
