# Generated by Django 5.0.7 on 2024-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_remove_post_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='thread',
            name='topic_image',
            field=models.ImageField(default=1, blank=True, null=True, upload_to='images/'),
        ),
    ]
